import './arrow.svg';
import './basket.svg';
import './logoSmall.svg';
import './logo.svg';
import './search.svg';
import './icon.svg';
import './icon1.svg';
import './icon2.svg';
import './close.svg';